return {
  {
    "nvim-treesitter/nvim-treesitter",
    keys = {
      { "<c-space>", false },
      { "<Enter>", desc = "Increment selection" },
    },
    opts = {
      ensure_installed = {
        "bash",
        "blueprint",
        "c",
        "cmake",
        "cpp",
        "diff",
        "dockerfile",
        "glsl",
        "git_commit",
        "html",
        "java",
        "javascript",
        "json",
        "kconfig",
        "kotlin",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "make",
        "org",
        "python",
        "rst",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<Enter>",
          node_incremental = "<Enter>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },
  {
    "HiPhish/nvim-ts-rainbow2",
    lazy = true,
  },
}
